blank_issues_enabled: true
contact_links:
  - name: Frequently asked questions 📃
    url: https://doc.episciences.org/faq/
    about: Questions regarding Episciences? Take a look at our FAQs
  - name: Documentation 💻
    url: https://doc.episciences.org/
    about: Take a look at our documentation
  - name: Support questions 💬
    url: https://www.episciences.org/page/support
    about: Other type of issue? Ask for support